---

# Homebrew
- name: Configure dnsmasq (Homebrew)
  lineinfile:
    dest: /usr/local/etc/dnsmasq.conf
    regexp: "^address=\\/{{ dnsmasq_domain }}\\/127\\.0\\.0\\.1"
    line: "address=/{{ dnsmasq_domain }}/127.0.0.1"
  when: ansible_pkg_mgr == 'homebrew'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Homebrew is supported)"
  when: ansible_pkg_mgr != 'homebrew'

# Common
- name: mkdir /etc/resolver
  file:
    path: /etc/resolver
    owner: root
    group: wheel
    state: directory

- name: configure system
  copy:
    src: resolver
    dest: /etc/resolver/{{ dnsmasq_domain }}
    owner: root
    group: wheel
    mode: 0644
